---
- hosts: developer-workstation
  remote_user: root
  become: yes
  tasks:
  - name: Import the public key used by the package management system
    apt_key: keyserver=https://www.mongodb.org/static/pgp/server-4.0.asc state=present
  - name: Add MongoDB repository
    apt_repository: repo='deb [ arch=amd64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse' state=present
  - name: install mongodb
    apt: pkg=mongodb-org state=latest update_cache=yes
    notify:
    - start mongodb
  handlers:
  - name: start mongodb
    service: name=mongod state=started